DROP DATABASE IF EXISTS database;
DROP USER IF EXISTS `admin`@`%`;
DROP USER IF EXISTS `user`@`%`;
CREATE DATABASE IF NOT EXISTS car_world CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER IF NOT EXISTS `caradmin`@`%` IDENTIFIED WITH mysql_native_password BY 'password';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, REFERENCES, INDEX, ALTER, EXECUTE, CREATE VIEW, SHOW VIEW,
CREATE ROUTINE, ALTER ROUTINE, EVENT, TRIGGER ON `car_world`.* TO `admin`@`%`;
CREATE USER IF NOT EXISTS `user`@`%` IDENTIFIED WITH mysql_native_password BY 'password';
GRANT SELECT, INSERT, UPDATE, DELETE, SHOW VIEW ON `car_world`.* TO `caruser`@`%`;
FLUSH PRIVILEGES;